# Markdownlint configuration
# See https://github.com/igorshubovych/markdownlint-cli#configuration

# Line length rule - disabled for comprehensive documentation
MD013: false

# Allow duplicate headers (common in documentation)
MD024:
  allow_different_nesting: true

# Allow inline HTML (useful for complex formatting)
MD033: false

# Allow trailing punctuation in headers
MD026: false
