# Pre-commit configuration for common.itsumi Helm library chart
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  # General file formatting and linting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=1024"]
      - id: trailing-whitespace
        exclude: '\.md$'
      - id: end-of-file-fixer
        exclude: '\.tgz$'
      - id: check-yaml
        args: ["--allow-multiple-documents"]
        exclude: 'templates/.*\.yaml$|.*\.jinja$'
      - id: check-json
      - id: check-case-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # Helm-specific linting
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: helmlint
        args: ["--values", "values.yaml"]

  # GitHub Actions linting
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: ["--fix", "--config", ".markdownlint.yaml"]
        exclude: 'CHANGELOG\.md$|starter-template/.*\.md\.jinja$'
