name: ✨ Feature Request
description: Suggest a new feature or enhancement for the common.itsumi library chart
title: "[Feature]: "
labels: ["feature-request", "triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: dropdown
    id: template-type
    attributes:
      label: Template Type
      description: What type of template or feature is this related to?
      options:
        - Deployment
        - Service
        - ConfigMap
        - Secret
        - Job
        - HPA
        - Ingress
        - Gateway API (HTTPRoute/GRPCRoute)
        - Argo Rollouts
        - Helper function
        - Documentation
        - CI/CD
        - Other
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Usage
      description: Provide an example of how this feature would be used
      render: yaml
      placeholder: |
        # Example values.yaml
        newFeature:
          enabled: true
          # ...

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: dropdown
    id: breaking-change
    attributes:
      label: Breaking Change
      description: Would this be a breaking change?
      options:
        - "No"
        - "Yes"
        - "Unsure"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
