name: 'Setup Helm'
description: 'Set up Helm with the standard version used across all workflows'

inputs:
  version:
    description: 'Helm version to install'
    required: false
    default: 'v3.18.4'

runs:
  using: 'composite'
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v4
      with:
        version: ${{ inputs.version }}
